### ISSUE TITLE
How to connect database?

### ISSUE THREAD

**Issue by vafrcor** [antkahn/flask-api-starter-kit#18]
I have run these command:
- `make install` >> install python dependencies
- `make database.connect` >> unable to connect to container
- `make database.migrate` >> unable to connect to database (see attachment below)

![Screen Shot 2020-07-14 at 07 17 22](https://user-images.githubusercontent.com/2148366/87366109-166f7b00-c5a2-11ea-9231-224869eb6a91.png)

any thought about this?  
thank you

**Comment by zacgottschall** [comment]
i'm getting a similar issue

**Comment by zacgottschall** [comment]
I added the following in `docker-compose.yml`

```
db:
    image: postgres:9.4
    volumes_from:
      - dbdata
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
```

fixed the issue for me
